pipeline {
    agent any
    environment {
        VENV = "venv"
    }
    stages {
        stage('Clone Repository') {
            steps {
                git credentialsId: 'github-credentials-id', url: 'https://github.com/Mohameddek1/alx-backend-python.git'
            }
        }
        stage('Set up Python Environment') {
            steps {
                sh '''
                python -m venv $VENV
                source $VENV/bin/activate
                pip install --upgrade pip
                pip install -r messaging_app/requirements.txt
                '''
            }
        }
        stage('Run Tests') {
            steps {
                sh '''
                source $VENV/bin/activate
                pytest messaging_app --junitxml=report.xml
                '''
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
    }
}
